name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-build
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA go
      - run: go test
  staticcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA go-tools
      - run: staticcheck ./...
  gofmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA go
      - run: test -z "$(gofmt -l .)"
  nixpkgs-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA nixpkgs-fmt
      - run: |
          find . -name '*.nix' -print0 | while IFS= read -r -d '' file; do
            nixpkgs-fmt --check "$file"
          done
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA actionlint
      - run: actionlint
